# Generated by Django 4.1.1 on 2022-09-16 17:11

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='uploadfile',
            field=models.FileField(blank=True, upload_to=files.models.directory_path, verbose_name='Files'),
        ),
    ]
