# Generated by Django 3.2.15 on 2022-09-19 23:44

from django.db import migrations
import files.file_ext_valid
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_files_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='uploadfile',
            field=files.file_ext_valid.ContentTypeRestrictedFileField(blank=True, upload_to=files.models.directory_path, verbose_name='Files'),
        ),
    ]
